version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/lab259/go-package-boilerplate
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - deps-{{ .Branch }}-
            - deps-
      - run:
          name: Setup .netrc
          command: |
            echo "machine github.com" > $HOME/.netrc
            echo "    login $GITHUB_USERNAME" >> $HOME/.netrc
            echo "    password $GITHUB_TOKEN" >> $HOME/.netrc
      - run:
          name: Installing Ginkgo
          command: go get -u github.com/onsi/ginkgo/ginkgo
      - run:
          name: Installing dependencies
          command: make dep-ensure
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Run tests
          command: |
            make coverage-ci
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: test-results
